### ISSUE TITLE
Floppy emulation works but occasionally has recoverable (hit retry) read errors 

### ISSUE THREAD

**Issue by h5n1xp** [h5n1xp/Omega#10]
> I had some read errors, always pressed retry and that fixed it, maybe they are more important than sound at the moment ...
> 
> But hey ADF reader works brilliantly thanks @dirkwhoffmann and @h5n1xp. You have done it !!

Ok @mithrendal I had a quick play this morning to see if I could make the disk errors more consistent, and it seems to be related to my "disk rotation" emulation. If I stop pretending that there is a rotation disk feeding the DMA (i.e. random start position when reading a track) and simply let it read in a whole track from start to finish, trackdisk.device considers the disk to be unreadable!

**Comment by h5n1xp** [comment]
I seem to be able to reduce the disk errors, by stopping the read head at a consistent position... I have chosen 1088, which, in our artificially created mfm data stream, is one sector in. 

This needs more investigation, but not a high priority right now.

**Comment by dirkwhoffmann** [comment]
I would put it on high prio, because it's likely that you read in wrong bytes. Hence, you might be hunting bugs that aren't there.

**Comment by h5n1xp** [comment]
> I would put it on high prio, because it's likely that you read in wrong bytes. Hence, you might be hunting bugs that aren't there.

Ok, but I'm out of ideas at the moment. I'm going to explore what happens when I reset the drive head to different positions a bit later. i need more consistent errors to understand what is going wrong.

Right now I want to know why AIBB (Amiga Intuition Based Benchmark) application halts during startup...   (it doesn't freeze, the gui caries on working, so it must be waiting for something).

**Comment by h5n1xp** [comment]
I spent the evening writing a new Floppy Drive emulation, somehow it manages to introduce even more read/write errors... it’s times like this when I wish the Amiga had a proper floppy controller rather than just hacking together the CIAs ☹️

**Comment by dirkwhoffmann** [comment]
Just a few ideas ...

When I did rewrites in VirtualC64, I usually created a second component (in your case a second disk controller) which run side by side to the old one. Then I added a couple of asserts checking that both implementations are completely the same. In almost any case, one or the other assertions hit. I know that such a "reference implementation" approach sounds unusual, but we're developing a special kind of software here. With being special, I don't refer to the functionality (which is special, too), but the fact that it's hard to write unit tests for it. Usually, an experienced software developer would have a decent unit-test suite at hand to quickly check that no errors get introduced. 

Secondly, it might be an option to look into an existing emulator and find the location where the byte stream comes from the disk. It might help to dump the byte stream into the console or a file and do a one to one comparison with the byte stream of Omega. I had to do such things with VICE and VirtualC64 a couple of times, but under much worse circumstances (I had to start dumping out sprite register data traces at a specific X, Y position after a couple of certain CPU instructions had been processed). SAE can be debugged with the Chrome dev tools directly in the browser, so I would look at this emulator first. 

I know that everyone has a personal style to debug software. Hence, I'm not claiming that what I propose is the best way to go. I just wrote it to tell you what helped me in the past.

**Comment by h5n1xp** [comment]
Just as you posted this, I found the bug! The active floppy drive was still reporting it's state on the CIA A PRA, even when no drive was selected in CIA B PRB... adjusting that has eliminated the errors completely.

**Comment by dirkwhoffmann** [comment]
👍👍👍

**Comment by h5n1xp** [comment]
As a nice bonus, multiple drives now work. I will update the sources within the hour... need to clean out all my debugging printf()s..
