### ISSUE TITLE
Implement HAM-6 Mode

### ISSUE THREAD

**Issue by h5n1xp** [h5n1xp/Omega#15]
I wasn't planning the support HAM mode. But this does seem an interesting challenge, and one which I'm keen to attempt.

This is a very low priority. But I will be adding features to the display generation to support it.

**Comment by h5n1xp** [comment]
Ran into an interesting issue last night, each bitplane dat register contains 16pixels worth of data (which fits into 2 bytes). So when generating the display, chunky pixels are created in pairs:

1 and 9
2 and 10
3 and 11
4 and 12
5 and 13
6 and 14
7 and 15
8 and 16

You get the idea. But HAM pixels depend upon the pixel to the left. In my display generator pixel 9 doesn’t have a left pixel (pixel 8) during its generation cycle!! 

So I’ve had to generate the first 8 pixels, and then the second 8. Not super happy about this, as it doubles the time taken to generate. Not really a problem I suppose, as HAM isn’t really used that much.

**Comment by mithrendal** [comment]
Photon paint is using HAM. Maybe a good testcase...

**Comment by h5n1xp** [comment]
If you build from the latest source, HAM6 is working now... But it will demand a lot of CPU, my code is not optimised in any way. Please have a play if you can (I've been testing with Paint 4).
