### ISSUE TITLE
Paula IRQ logic

### ISSUE THREAD

**Issue by dirkwhoffmann** [h5n1xp/Omega#22]
I’ve checked how Paula’s IRQ handler is implemented in Miming. They do exactly what I expected: There is some combinatorial logic with INTENA and INTREQ as inputs an the three interrupt level lines as output: 

    always @(intena or intreq)
    begin
    	//and int enable and request signals together
	if (intena[14])
		intreqena[14:0] = intreq[14:0] & intena[14:0];
	else
		intreqena[14:0] = 15'b000_0000_0000_0000;	
    end

    //interrupt priority encoder
    always @(posedge clk)
    begin
	casez (intreqena[14:0])
		15'b1?????????????? : _ipl <= 1;
		15'b01????????????? : _ipl <= 1;
		15'b001???????????? : _ipl <= 2;
		15'b0001??????????? : _ipl <= 2;
		15'b00001?????????? : _ipl <= 3;
		15'b000001????????? : _ipl <= 3;
		15'b0000001???????? : _ipl <= 3;
		15'b00000001??????? : _ipl <= 3;
		15'b000000001?????? : _ipl <= 4;
		15'b0000000001????? : _ipl <= 4;
		15'b00000000001???? : _ipl <= 4;
		15'b000000000001??? : _ipl <= 5;
		15'b0000000000001?? : _ipl <= 6;
		15'b00000000000001? : _ipl <= 6;
		15'b000000000000001 : _ipl <= 6;
		15'b000000000000000 : _ipl <= 7;
		default:			  _ipl <= 7;
	endcase
    end

Don’t get confused by the IRQ levels. The bit values are logically inverted. Hence a value of 1 triggers a level 6 interrupt.

The Omega code is almost similar to this with an exception. In Omega, if I disable the (global) INTEN bit, the CPU IRQ lines are not changed. In Miming, they would go down to 0.

**Comment by h5n1xp** [comment]
Fantastic catch! 

I think this explains quite a few problems we see with Omega. Last night I was trying to write some test programs, so I could test blitter and bitplane code, but once I entered a forbid() state, the Emulator would lock up!

**Comment by dirkwhoffmann** [comment]
My own emulator is giving me a hard time, too. It's running in an endless loop now 😟. 

I think I have to work on the drive identification stuff. Before Kickstart displays this picture, it has to check if there is a drive with a disk in it. The picture only shows up if this test fails. I haven't implemented any disk stuff yet, so that might be the cause for my infinite loop.

**Comment by h5n1xp** [comment]
I don’t think I needed any floppy emulation at all early on... the most important parts, to get to the kickstart screen are the CIAs and the Blitter.

-edit- are you able to just take Omega’s floppy drive emulation and use that? It’s not as clean or elegant as vAmigas code, but it should give you a good starting point!

Also, df0: doesn’t appear to  need to identify itself for the Amiga to recognise it.

**Comment by dirkwhoffmann** [comment]
Yes, you're right. Once my CIAs switch to idle mode (sleep logic), they never ever wake up again. Hence, vAmiga is effectively running without CIAs so far.

**Comment by dirkwhoffmann** [comment]
OMG, I've just discovered the most stupid bug of all times 😲. It's right there in my own code 🤭: 

    void CIA::wakeUp(Cycle targetCycle)
    {
        if (sleeping) return;
       ...

Unfortunately, the code is already on Github, so the whole world can see it 🙈.

The fix was easy though: 

    void CIA::wakeUp(Cycle targetCycle)
    {
        if (!sleeping) return;
       ...

Now, vAmiga doesn't hang in an infinite loop any more 😃. It moved on to explore some extraterrestrial Kickstart space where it had never been before. Unfortunately, the party didn't last long. It stopped in frame 87:

    [87]  FE49B4: WARNING: pokeCustom16(DFF034 [POTGO], 0): MISSING IMPLEMENTATION

The good thing is: Now I know what to work on next, the POTGO register.

**Comment by h5n1xp** [comment]
Make sure you have your CIA timers running, AmigaOS needs those!

**Comment by h5n1xp** [comment]
> OMG, I've just discovered the most stupid bug of all times 😲. It's right there in my own code 🤭:
> 
> ```
> void CIA::wakeUp(Cycle targetCycle)
> {
>     if (sleeping) return;
>    ...
> ```
> Unfortunately, the code is already on Github, so the whole world can see it 🙈.
> 
> The fix was easy though:
> 
> ```
> void CIA::wakeUp(Cycle targetCycle)
> {
>     if (!sleeping) return;
>    ...
> ```

I’ve made far worse bugs, and ones that my code actually ended up relying on 😂!

> Now, vAmiga doesn't hang in an infinite loop any more 😃. It moved on to explore some extraterrestrial Kickstart space where it had never been before. Unfortunately, the party didn't last long. It stopped in frame 87:
> 

👍🏻👍🏻👍🏻

> ```
> [87]  FE49B4: WARNING: pokeCustom16(DFF034 [POTGO], 0): MISSING IMPLEMENTATION
> ```
> The good thing is: Now I know what to work on next, the POTGO register.

Are you sure about a write to potgo? That doesn’t seem right. Put a printf() in my potgo function. And see how many time it’s called in Omega.

**Comment by dirkwhoffmann** [comment]
Omega writes a 0 into POTGO, too 😎. It makes sense, because POTGO contains port direction bits. Writing a 0 configures alls these bits as inputs.

**Comment by h5n1xp** [comment]
> Omega writes a 0 into POTGO, too 😎.

Yay, Omega is useful!! 😊

> It makes sense, because POTGO contains port direction bits. Writing a 0 configures alls these bits as inputs.

Yes, you are correct, this does make sense.

**Comment by h5n1xp** [comment]
> The Omega code is almost similar to this with an exception. In Omega, if I disable the (global) INTEN bit, the CPU IRQ lines are not changed. In Miming, they would go down to 0.


Ok, added and extra condition, if the master interrupt bit is set to 0, the CPU IRQ level is set to 0. I think this now produces the correct behaviour.


    void checkInterrupt(Chipset_t* chipset){
    
    if(chipset->intenar & 0x4000){ // if master interrupt switch is enabled
        
        uint16_t intMask = chipset->intreqr & chipset->intenar; //only set the int level, if bits are enabled
        
        if(intMask !=0){
            
            m68k_end_timeslice();
            
            if(intMask & 8192){  // External int
                m68k_set_irq(6);
            }else if(intMask & 4096){ // Disk sync
                m68k_set_irq(5);
            }else if(intMask & 2048){ // Serial receive buffer full
                m68k_set_irq(5);
            }else if(intMask & 1024){ // Audio 3
                m68k_set_irq(4);
            }else if(intMask & 512){  // Audio 2
                m68k_set_irq(4);
            }else if(intMask & 256){  // Audio 1
                m68k_set_irq(4);
            }else if(intMask & 128){  // Audio 0
                m68k_set_irq(4);
            }else if(intMask & 64){   // Blitter finished
                m68k_set_irq(3);
            }else if(intMask & 32){   // VBL
                m68k_set_irq(3);
            }else if(intMask & 16){   // Copper
                m68k_set_irq(3);
            }else if(intMask & 8){    // Ports, IO and timers
                m68k_set_irq(2);
            }else if(intMask & 4){    // Software int
                m68k_set_irq(1);
            }else if(intMask & 2){    // Disk block finished
                m68k_set_irq(1);
            }else if(intMask & 1){    // Serial Transmit buffer empty
                m68k_set_irq(1);
            }
            
        }else{
            m68k_set_irq(0);    // no interupt pending
        }
        
    }else{
        m68k_set_irq(0);    // no interupt if master INT disabled
    }
    
    }



This doesn't seem to have changed Omega's stability.

**Comment by h5n1xp** [comment]
Closing issue for now... interrupts seem to work as expected for now. Will reopen if more inconsistency is found.

**Comment by h5n1xp** [comment]
Hey Dirk, what settings are you using for the M68K_INT_ACK_CALLBACK(A)? 
Since we have Paula, I just turn this call back off... Perhaps we need something more sophisticated?

**Comment by dirkwhoffmann** [comment]
I think the Amiga doesn't use acknowledged interrupts. I also disabled the callback.
