### ISSUE TITLE
Blitter zero flag

### ISSUE THREAD

**Issue by dirkwhoffmann** [h5n1xp/Omega#25]
If I understand the Omega code correctly, the zero flag is set or cleared after each word operation:  

    //Zero Flag
     if(channelD==0){
         chipset->dmaconr = chipset->dmaconr | 0x2000;   //set zero flag
     else {
         chipset->dmaconr = chipset->dmaconr & 0xDFFF; // clear zero flag
     }

But isn't the zero flag supposed to observe the whole blit operation? I understood it to work as follows: When a blit operation is startet, the flag is set to true. Once there is something in D not equal to 0, the flag is cleared.

**Comment by h5n1xp** [comment]
Another bug, well spotted! I really appreciate your review here.
