### ISSUE TITLE
compiling and linking problems...

### ISSUE THREAD

**Issue by mithrendal** [h5n1xp/Omega#4]
Hi @h5n1xp ,

I like to run Omega but I did fail. 

1.) I firstly set up an empty c console project in Xcode8.2 with a main.c which just prints "hello world"
+that runs fine !
2.) Then I linked SDL2 to it.
+that runs fine !
3.) dragged  all omega files into it. Which replaced the existing main.c with yours. 
compiled it. And it gives error
   no m68kconf.h found.... which is referenced by m68k.h 
   that file does not exists. I took it from the musashi core. (out from from vAmiga 😬)
4.) now that is done. It complains that it chipset.c  about not knowing low16Meg
  I added a maybe missing (?) #include memory.h into chipset.c
5.) now it compiles. 🎉 But at linking stage it complains about
![grafik](https://user-images.githubusercontent.com/17108995/53040331-6fa4af00-3481-11e9-9899-05a6fd6b7c13.png)

what am I doing wrong ?? Are there maybe still some files missing ?

**Comment by h5n1xp** [comment]
Hang on! let me check now!

I have added the missing m68kconfig file, try with that one.

**Comment by h5n1xp** [comment]
I have attached a MacOS build for you, to play with while you get it compiling. If you have more linking errors, are you able to send me more of the error, the screenshot you posted don't give me quite enough information to see what is actually failing.


[Omega.zip](https://github.com/h5n1xp/Omega/files/2881753/Omega.zip)

**Comment by mithrendal** [comment]
nice ! Thanks mate. Now it compiles, links and runs out of the box. That m68kconf.h file was missing. No need to patch a #include "memory.h" in chipset.c because it is now already included in your m68kconf.h file. 
I close the issue now.
