### ISSUE TITLE
Can someone help with ADF Block to MFM Sector function?

### ISSUE THREAD

**Issue by h5n1xp** [h5n1xp/Omega#6]
I spent most of today trying to write some code to convert an ADF image into an MFM image... It's been hard going and I can't seem to get it right.

But without such a function Omega can't use regular ADF files.

**Comment by dirkwhoffmann** [comment]
Did you solve the MFM translation problem?

**Comment by h5n1xp** [comment]
No, If you look in main.c I have written a function called expA2M(), which tried to build an MFM image from an ADF, but it doesn't boot... several problems could exist, but the first problem is that my header and data checksum is just a look of xors... does any one know the actual algorithm? I may need to look into UAE disk.c and see what that is doing.

**Comment by dirkwhoffmann** [comment]
You'll find a lot of disk resources in Grote Gelfland Abraham's book: Amiga Disk Drives In And Out

I also started to assemble some info about the disk here: 
https://github.com/dirkwhoffmann/vAmiga/wiki/Amiga-Disk

What I didn't find out so far is the track order. I guess the order is track 0, 1, 2, …, 159, but I wasn't able to confirm this yet.

**Comment by h5n1xp** [comment]
Amiga disks are a bit odd, the trackdisk.device writes an entire track at once so the sectors are just written wherever the disk head is at the time to write starts, there is come commented out code in my main function which prints out the structure of the UAE encoded MFM disks (which do work), that gives real insight. I will look at your link in a bit Many thanks!!

Ok, the tracks are written from the outside to the inside, lower surface then upper surface (2 track per cylinder), in that order.

**Comment by h5n1xp** [comment]
Now my display generation, copper, blitter, and keyboard and mouse are working well enough to run workbench and DPaint, this has become the most serious issue, as really we need to be able to more easily load disks without having to encode them with WinUAE first.

**Comment by dirkwhoffmann** [comment]
I've just opened FLOPPY.C... let's see what they do...

**Comment by mithrendal** [comment]
I can see the top-level entry functions are at the end of the file, low level at the beginning ...

found this:
  floppySectorMfmDecode(UBY *src, UBY *dst, ULO track)
and its brother
  floppySectorMfmEncode(ULO tra, ULO sec, UBY *src, UBY *dest, ULO sync)
 ...

**Comment by dirkwhoffmann** [comment]
Hmm, I'm also a little bit confused now. I've found this: 

    /* Preamble and sync */
    
      *(dest + 0) = 0xaa;
      *(dest + 1) = 0xaa;
      *(dest + 2) = 0xaa;
      *(dest + 3) = 0xaa;
      *(dest + 4) = (UBY) (sync>>8);
      *(dest + 5) = (UBY) (sync & 0xff);
      *(dest + 6) = (UBY) (sync>>8);
      *(dest + 7) = (UBY) (sync & 0xff);
        /* Track and sector info */

      tmp = 0xff000000 | (tra<<16) | (sec<<8) | (11 - sec);
      even = (tmp & MFM_MASK);
      odd = ((tmp>>1) & MFM_MASK);
      *(dest +  8) = (UBY) ((odd & 0xff000000)>>24);
      *(dest +  9) = (UBY) ((odd & 0xff0000)>>16);
      *(dest + 10) = (UBY)((odd & 0xff00) >> 8);
      *(dest + 11) = (UBY)(odd & 0xff);
      *(dest + 12) = (UBY)((even & 0xff000000) >> 24);
      *(dest + 13) = (UBY)((even & 0xff0000) >> 16);
      *(dest + 14) = (UBY)((even & 0xff00) >> 8);
      *(dest + 15) = (UBY)(even & 0xff);

This fits (almost) well with the explanation in the floppy book:

<img width="613" alt="screenshot 2019-02-23 at 09 30 29" src="https://user-images.githubusercontent.com/12561945/53283975-f1c8f800-374d-11e9-88d6-30a74bfc1bae.png">

<img width="482" alt="screenshot 2019-02-23 at 09 30 52" src="https://user-images.githubusercontent.com/12561945/53283976-f42b5200-374d-11e9-8baa-fde557b2d716.png">

However, I don't find any code computing the MFM clock bits. It's correct the odd bits are stored first, but the clock bit positions are simply set to 0 by the MFM_MASK. The original MFM code required the clock bit to be 1 iff the left and right data bit are both 0.

**Comment by h5n1xp** [comment]
Unfortunately I don’t have time to look at it myself today... but perhaps it add the mfm encoring once the odd even splits are done, if you look at my code, that’s how I do it.

-edit- perhaps, the mfm coding is done during the data reading stream...

**Comment by dirkwhoffmann** [comment]
I started looking at your code. It's pretty clean and I think I understand what you're doing. 

Function expA2M looks OK to me. (First I got confused by the 'offset' variable because of the '+1's, but the variable is not used any more. You're counting the sectors with variable 'count' now).
I also checked function clocking() which looks OK.
SYNC marks seems to be OK, too. 

From an overall point of view, your code looks correct. It might simply be a bug with respect to some index or so, but wasn't able to spot an error yet. 

BTW, I also checked WinFollow's read function, but I still don't find any code that sets the clock bits.

**Comment by h5n1xp** [comment]
> I started looking at your code. It's pretty clean and I think I understand what you're doing.
> 
> Function expA2M looks OK to me. (First I got confused by the 'offset' variable because of the '+1's, but the variable is not used any more. You're counting the sectors with variable 'count' now).
> I also checked function clocking() which looks OK.
> SYNC marks seems to be OK, too.
> 
> From an overall point of view, your code looks correct. It might simply be a bug with respect to some index or so, but wasn't able to spot an error yet.
> 
> BTW, I also checked WinFollow's read function, but I still don't find any code that sets the clock bits.

Sorry, my code was cobbled together during breaks at work, so it has a lot of messy variables and soforth! Thank you for reviewing it! The output “looks” like MFM code... and seems to decode properly... except by trackdisk :)

-Edit- is it possible the Amiga only needs the clocking bits for the sync? The rest will be masked so it doesn’t matter!?

**Comment by dirkwhoffmann** [comment]
I've noticed that you've checked in files raw2.adf to raw5.adf. According to the size of the files, they are MFM coded ADF files (translated by UAE). Can you provide the original ADFs as well?

I'm planning to postpone my work on the Copper and to implement the MFM conversion into my emulator first. Having the original ADFs, I can make a byte to byte comparison o the result with the UAE exports. 

"-Edit- is it possible the Amiga only needs the clocking bits for the sync? The rest will be masked so it doesn’t matter!?"

I was thinking in the similar direction. Maybe WinFollow simply ignores the clock bits completely. If the Rom routines are used for loading, the clock bits are deleted anyway. Nevertheless, emulating the clock bits  is more compatible (and not very difficult). Interestingly, they don't affect the checksum, because the Amiga OS uses a trivial XOR logic to compute it.

**Comment by h5n1xp** [comment]
I have added the original ADF files to the repository called original2 and original5

**Comment by dirkwhoffmann** [comment]
OK, thanks! Now we have a reference test case to work on...

BTW, although your code for adding clock bits seems to be correct, you could replace it by something simpler. Something like this: 

    static const uint64_t MFM_DATA_BIT_MASK64  = 0x5555555555555555;
    static const uint64_t MFM_CLOCK_BIT_MASK64 = 0xAAAAAAAAAAAAAAAA;

    uint64_t
    Disk::addClockBits(uint64_t value, uint64_t previous)
    {
        // Clear all previously set clock bits
        value &= MFM_DATA_BIT_MASK64;

        // Compute clock bits (clock bit values are inverted)
        uint64_t lShifted = (value << 1);
        uint64_t rShifted = (value >> 1) | (previous << 63);
        uint64_t cBitsInv = lShifted | rShifted;

        // Reverse the computed clock bits
        uint64_t cBits = cBitsInv ^ MFM_CLOCK_BIT_MASK64;
    
        // Return original value with the clock bits added
        return value | cBits;
    }

**Comment by dirkwhoffmann** [comment]
lowlevelSector[5] = sector << 1 | side;

Shouldn't this be the track number? 🤔

**Comment by h5n1xp** [comment]
> ```
> lowlevelSector[5] = sector << 1 | side;
> ```
> 
> Shouldn't this be the track number? 🤔

Yes, there are probably loads of bugs like this ☹️ 

If you get the sector encoding to work, I'm going to have to rewrite the floppy handing code anyway, as it is yet another nasty hack.

-edit- ok, tonight, I’ll rewrite the code to properly handle the floppy disk images, rather than just assuming offsets into the data blob.

**Comment by dirkwhoffmann** [comment]
Actually, the code is pretty good already. There are just a few bugs to rule out.

I think there is another one in your checksum computation: 

    uint32_t sum =0;
                for(int i = 4; i < 22;++i){
                    sum ^=lowlevelSector[I];

Although sum is a 32 bit value, your checksum is only 8 bit, because you're iterating through lowlevelSector which is a byte array.

WinFellow shows that you have to step through in word steps: 

    for(x = 8; x < 48; x += 4)
    {
     hck ^= (((ULO) *(dest + x))<<24) | (((ULO) *(dest + x + 1))<<16) |
 	    (((ULO) *(dest + x + 2))<<8) |  ((ULO) *(dest + x + 3));
    }

Also WinFellow computes the checksum on the data where odd and even bits are already split.

**Comment by dirkwhoffmann** [comment]
I'm posting my current implementation here together with a small "lessons learned". (I'm not able to test my code yet, but it should give you my idea): 


    void
    Disk::encodeSector(ADFFile *adf, Track t, Sector s)
    {
    assert(isTrackNumber(t));
    assert(isSectorNumber(s));
    
    /* Block header layout:
     *                     Start  Size   Value
     * Bytes before SYNC   00      4     0xAA 0xAA 0xAA 0xAA
     * SYNC mark           04      4     0x44 0x89 0x44 0x89
     * Track & sector info 08      8     Odd/Even encoded
     * Unused area         16     32     0xAA
     * Block checksum      48      8     Odd/Even encoded
     * Data checksum       56      8     Odd/Even encoded
     */

    uint8_t *p = data.track[t] + (s * mfmBytesPerSector);
    
    // Bytes before SYNC
    p[0] = 0xAA;
    p[1] = 0xAA;
    p[2] = 0xAA;
    p[3] = 0xAA;

    // SYNC mark
    uint16_t sync = 0x4489;
    p[4] = HI_BYTE(sync);
    p[5] = LO_BYTE(sync);
    p[6] = HI_BYTE(sync);
    p[7] = LO_BYTE(sync);

    // Track and sector information
    uint8_t info[4] = { 0xFF, (uint8_t)t, (uint8_t)s, (uint8_t)(11 - s) };
    encodeOddEven(&p[8], info, sizeof(info));
    
    // Unused area
    for (unsigned i = 16; i < 48; i++)
        p[i] = 0xAA;
    
    // Data
    uint8_t bytes[512];
    adf->readSector(bytes, t, s);
    encodeOddEven(&p[64], bytes, sizeof(bytes));
    
    // Block checksum
    uint8_t bcheck[4] = { 0, 0, 0, 0 };
    for(unsigned i = 8; i < 48; i += 4) {
        bcheck[0] ^= p[i];
        bcheck[1] ^= p[i+1];
        bcheck[2] ^= p[i+2];
        bcheck[3] ^= p[i+3];
    }
    encodeOddEven(&p[48], bcheck, sizeof(bcheck));
    
    // Data checksum
    uint8_t dcheck[4] = { 0, 0, 0, 0 };
    for(unsigned i = 64; i < 1088; i += 4) {
        dcheck[0] ^= p[i];
        dcheck[1] ^= p[i+1];
        dcheck[2] ^= p[i+2];
        dcheck[3] ^= p[i+3];
    }
    encodeOddEven(&p[56], dcheck, sizeof(bcheck));
    
    // Add clock bits
    for(unsigned i = 8; i < 1088; i ++)
        p[i] = addClockBits(p[i], p[i-1]);
    }

Decisions / Lessons learned: 

- Your `encodeBlock` functions makes the code pretty clean.  I adapted that (just renamed it to `encodeOddEven` in my code.
- I also adapted your approach to add the clock bits at the end.
- I changed my `addClockBits` function to take uint8_t values in order to avoid big endian / little endian issues (speed is not an issue here).
- I didn't adapt your two stage approach (you're first setting up `lowLevelSector` and doing the encoding afterwards). I got confused a couple of times because of the changing index position, so I think it's better to do the encoding in a single pass.
- I used an uint8_t array in the checksum computation to avoid any little endian / big endian issues.

**Comment by dirkwhoffmann** [comment]
I've started looking into the raw images produced by UAE:

    hexdump -n 200 raw2.adf 
    0000000 55 41 45 2d 31 41 44 46 00 00 00 a6 00 00 00 01
    0000010 00 00 31 fe 00 01 8b e0 00 00 00 01 00 00 31 fe
    0000020 00 01 8b e0 00 00 00 01 00 00 31 fe 00 01 8b e0

 No clock bits 😲. What's UAE doing here???

Also, the image doesn't start with the 4 x 0xAA sequence which is produced by our decoders. 

This is what my current encoder produces: 

    0000000 aa aa aa aa 44 89 44 89 55 2a aa a9 44 aa aa aa
    0000010 aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa
    0000020 aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa

**Comment by h5n1xp** [comment]
> I've started looking into the raw images produced by UAE:
> 
> ```
> hexdump -n 200 raw2.adf 
> 0000000 55 41 45 2d 31 41 44 46 00 00 00 a6 00 00 00 01
> 0000010 00 00 31 fe 00 01 8b e0 00 00 00 01 00 00 31 fe
> 0000020 00 01 8b e0 00 00 00 01 00 00 31 fe 00 01 8b e0
> ```
> No clock bits 😲. What's UAE doing here???
> 
> Also, the image doesn't start with the 4 x 0xAA sequence which is produced by our decoders.
> 
> This is what my current encoder produces:
> 
> ```
> 0000000 aa aa aa aa 44 89 44 89 55 2a aa a9 44 aa aa aa
> 0000010 aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa
> 0000020 aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa
> ```

Sorry, I’m away from my laptop today, the UAE image starts with a header (I think I have recorded it in Floppy.h) which details the tracks (took me ages to figure out what is going on here) The first 2004bytes are not disk data.

/* UAE-1ADF (ADF_EXT2)
 * W reserved
 * W number of tracks (default 2*80=160)
 *
 * W reserved
 * W type, 0=normal AmigaDOS track, 1 = raw MFM (upper byte = disk revolutions - 1)
 * L available space for track in bytes (must be even)
 * L track length in bits
 *
 */

The track data follows, each ADF track is 12798 bytes long, with  unused bytes at the end of the track just zeros, there is more space in the ADF track than needed for an amigaOS floppy. In my track read function I have to wrap around before the zeros are fed to the Amiga! Current I just ignore the ADF header as all the disk images I use are standard Amiga Format which always has the same offsets into the file.

**Comment by dirkwhoffmann** [comment]
Ah, OK, it looks better after the header: 

    0000bd0 aa aa aa aa aa aa aa aa aa aa aa aa 44 89 44 89
    0000be0 55 2a a9 25 55 2a aa aa aa aa aa aa aa aa aa aa
    0000bf0 aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa

It doesn't match, but at least, I can see lots of clock bits now 👍.

**Comment by h5n1xp** [comment]
> Ah, OK, it looks better after the header:
> 
> ```
> 0000bd0 aa aa aa aa aa aa aa aa aa aa aa aa 44 89 44 89
> 0000be0 55 2a a9 25 55 2a aa aa aa aa aa aa aa aa aa aa
> 0000bf0 aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa
> ```
> It doesn't match, but at least, I can see lots of clock bits now 👍.

The Amiga just writes the disk track where ever the head happens to be at the time the write starts, so the track can start with anything! The track only makes sense once you have read the whole thing into memory.

These UAE created disk images, are actually produced by AmigaOS, they aren’t artificially created, so the sectors won’t be nice an neatly ordered.

-edit- sorry for all the edits, I’m outside with my daughter today, and replying between stopping her from eating mud (and worms 🙄)  😄

**Comment by dirkwhoffmann** [comment]
More confusion...

To get insight in the raw file that was produced by UAE, I've converted it (via hexdump magic) to a text file:

    hexdump -v -e '/ 1 "%02x "' raw2.adf > raw2.txt

Now I can open it in Sublime and use ordinary text search: 

<img width="1045" alt="screenshot 2019-02-24 at 15 50 37" src="https://user-images.githubusercontent.com/12561945/53300990-cdecdb80-384d-11e9-82a3-5aa965d48fd8.png">

Let's see what the highlighted parts are: 

In binary we have

    01010101 00101010 10101010 10101001 01010101 00101010 10101001 00101001

Kicking out all clock bits results in

    -1-1-1-1 -0-0-0-0 -0-0-0-0 -0-0-0-1 -1-1-1-1 -0-0-0-0 -0-0-0-1 -0-0-0-1

The odd and even bits have to be merged together as

    1-1-1-1-   0-0-0-0-  0-0-0-0-  0-0-0-1-
    -1-1-1-1   -0-0-0-0  -0-0-0-1  -0-0-0-1

which results in

    11111111 00000000  00000001  00000011

In hex we read
    
    FF 00 01 03

Hence, we have track 0, sector 1 in front of us. The fourth byte indicates the sectors to come which is 3 here. Our encoder uses a different byte ordering, so we don't produce the same header. This means that we cannot do a binary comparison, even if we align the data. 

What really confuses me is the area that comes next. If I did count correctly, the block header checksum is

    AA AA AA AA AA AA A9 24

and the data checksum is

    AA AA AA AA 00 00 00 00 

Where do all the 0's come from 😟. We are again in trouble with the clock bits.

It would be cool if we had a binary MFM stream that comes out of the UAE encoder directly. Is that possible? 

Mud and worms .... maybe a worm erased the disk? 🤔 I just remember how all these nasty boot block viruses drove me crazy back in the days.

**Comment by h5n1xp** [comment]
The zeros at the end of the track are unused, you need to wrap back around to the beginning of the track!

The ADF track is larger than the MFM data track on the disk

**Comment by mithrendal** [comment]
;-) Keep care of your daughter !!!

**Comment by dirkwhoffmann** [comment]
OK then, let's see where track 0, sector 0 is ...

Some more magic calculation reveals that we have to look for sequence 44 89 55 2A AA ?? 55 2A AA ??

Here we go: 

<img width="1045" alt="screenshot 2019-02-24 at 17 25 20" src="https://user-images.githubusercontent.com/12561945/53301968-5329bd80-3859-11e9-9ceb-587395e342db.png">

So the fourth byte is build out of AA A9 which results in 01.

I faked my encoder to produce 01 as the fourth entry for now to make the results comparable. This is what my encoder produces:


     hexdump -n 100 /tmp/adf.raw 
    0000000 aa aa aa aa 44 89 44 89 55 2a aa aa 55 2a aa a9
    0000010 2a aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa
    0000020 aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa
    0000030 aa aa aa aa aa aa aa a9 2a aa aa aa 55 29 49 24
    0000040 aa a5 29 2a 4a 92 a5 24 aa aa a9 12 a9 55 2a a4

😎

You can find my MFM encoder in the vAmiga sources at Amiga/Drive/Disk.cpp

**Comment by h5n1xp** [comment]
Cheers Dirk!! I'll have a try ASAP!

**Comment by h5n1xp** [comment]
I haven't had time to look at this, but something my code doesn't do is add in the track gap, when the sector countdown hits 1 the next "sector" is a track gap of 700 bytes usually staring with 0xAAA85555, AmigaOS uses this to know where the start of the track is located in memory.

**Comment by h5n1xp** [comment]
The first track of raw2 looks like this: 
1032: Track 0, Side: 0, Sector: 2 (10)
2120: Track 0, Side: 0, Sector: 3 (9)
3208: Track 0, Side: 0, Sector: 4 (8)
4296: Track 0, Side: 0, Sector: 5 (7)
5384: Track 0, Side: 0, Sector: 6 (6)
6472: Track 0, Side: 0, Sector: 7 (5)
7560: Track 0, Side: 0, Sector: 8 (4)
8648: Track 0, Side: 0, Sector: 9 (3)
9736: Track 0, Side: 0, Sector: 10 (2)
10824: Track 0, Side: 0, Sector: 0 (1)
12612: Track 0, Side: 0, Sector: 1 (11)

The track gap can be found after sector 0 on this track.

**Comment by h5n1xp** [comment]
Ok Dirk,

I used your Checksum code in my original function, and now it works (I have also added some code to generate valid track gap, please see main.c for details). 

Excellent work 👏

**Comment by h5n1xp** [comment]
@mithrendal Would you be kind enough to check the code still compiles on your machine and test some ordinary ADF files for me, thanks 👍 

I'm going to have to do a total rewrite of the floppy code soon, and remove the old polling section which it totally unnecessary now I don't really simulate a spinning disk.

**Comment by mithrendal** [comment]
Sure ! This evening when I am at home again I will give it a compile and test this puppy out...

**Comment by dirkwhoffmann** [comment]
I'm also eager to run the executables on my machine (I only have a Mac though).

**Comment by h5n1xp** [comment]
> I'm also eager to run the executables on my machine (I only have a Mac though).

If you want to test (and don't have time to build), here is a MacOS (Sierra) build attached.

[Omega.zip](https://github.com/h5n1xp/Omega/files/2900063/Omega.zip)

**Comment by dirkwhoffmann** [comment]
When I start it from Terminal with 

./Omega kick12.rom Workbench/A2000\ WB\ 1.2\ D.adf 

it doesn't continue to load. I continues to show the intro screen: 

<img width="752" alt="screenshot 2019-02-25 at 11 37 25" src="https://user-images.githubusercontent.com/12561945/53331781-0219d800-38f2-11e9-896a-0b37d10d61d4.png">

**Comment by h5n1xp** [comment]
> When I start it from Terminal with
> 
> ./Omega kick12.rom Workbench/A2000\ WB\ 1.2\ D.adf
> 
> it doesn't continue to load. I continues to show the intro screen:
> 
> <img alt="screenshot 2019-02-25 at 11 37 25" width="752" src="https://user-images.githubusercontent.com/12561945/53331781-0219d800-38f2-11e9-896a-0b37d10d61d4.png">

Hit F1 to trigger a "floppy insertion event", wait for the CIA to be polled.
F2 will remove the onscreen LEDs

**Comment by dirkwhoffmann** [comment]
Hitting F1 triggers a Df0 event (I see a debug message in the console), but it still doesn't boot the workbench 🙁.

**Comment by h5n1xp** [comment]
> Hitting F1 triggers a Df0 event (I see a debug message in the console), but it still doesn't boot the workbench .

What does F2 do? This is almost certainly an issues with key mapping in SDL

**Comment by h5n1xp** [comment]
Ahhh, no! This is the wrong build. You are seeing my IRQ issue... bare with me.

**Comment by h5n1xp** [comment]
Try this one.

[Omega.zip](https://github.com/h5n1xp/Omega/files/2900298/Omega.zip)

**Comment by dirkwhoffmann** [comment]
F1 only seems to work if it is pressed *before* the intro screen appears.

Now I got this 😲: 

<img width="752" alt="screenshot 2019-02-25 at 12 28 41" src="https://user-images.githubusercontent.com/12561945/53334411-039ace80-38f9-11e9-9354-79574012792a.png">

**Comment by h5n1xp** [comment]
> F1 only seems to work if it is pressed _before_ the intro screen appears.
> 
> Now I got this :
> 
> <img alt="screenshot 2019-02-25 at 12 28 41" width="752" src="https://user-images.githubusercontent.com/12561945/53334411-039ace80-38f9-11e9-9354-79574012792a.png">

Just "Retry" on all disk errors, they will work on second read. There is probably an IRQ issue with something (probably CIA related) getting out of sync during the data read, it always works when it tries the read again.

**Comment by dirkwhoffmann** [comment]
I tried Marble Madness: 

<img width="721" alt="screenshot 2019-02-25 at 12 31 30" src="https://user-images.githubusercontent.com/12561945/53334514-5e342a80-38f9-11e9-896e-d2f765438112.png">

It says: 

    16bit Write: Not implemented!

**Comment by h5n1xp** [comment]
> I tried Marble Madness:
> 
> <img alt="screenshot 2019-02-25 at 12 31 30" width="721" src="https://user-images.githubusercontent.com/12561945/53334514-5e342a80-38f9-11e9-896e-d2f765438112.png">
> 
> It says:
> 
> ```
> 16bit Write: Not implemented!
> ```

Ok, so it's tried to write to a chipset reg which I haven't implemented yet (like most of the sprites and audio stuff)... 

But wow! The disk booted, and thanks to your hard work! :smiley:

**Comment by dirkwhoffmann** [comment]
😎

<img width="752" alt="screenshot 2019-02-25 at 12 34 59" src="https://user-images.githubusercontent.com/12561945/53334718-dc90cc80-38f9-11e9-9c33-07e3a5bce603.png">

**Comment by h5n1xp** [comment]
I spent quite a bit of time tying to get dragable screens working, so please test. It doesn't work very well yet, but good enough to test software which rely upon such feature (DPaint's palette mixer for example). Although HAM produces some interesting results at the moment :laughing:

**Comment by mithrendal** [comment]
tested DMCS, quite complex intuition app ... works well (but as expected no sound)

![grafik](https://user-images.githubusercontent.com/17108995/53360205-36fb4e80-3935-11e9-9c5b-4019d36e36b6.png)

**Comment by h5n1xp** [comment]
Yes, It's difficult to implement sound in a platform independent way... Quite easy to make it work on top of SDL, so I'll probably put a bit of time onto it next month.

**Comment by mithrendal** [comment]
I also think sound is not so important for now ... I had some read errors, always pressed retry and that fixed it, maybe they are more important than sound at the moment ...

But hey ADF reader works brilliantly thanks @dirkwhoffmann and @h5n1xp. You have done it !!

**Comment by dirkwhoffmann** [comment]
If I remember correctly, the sample rate of each sound channel can be configured individually. Is this really easy to emulate? Maybe some kind of manual resampling is required 🤔.

**Comment by h5n1xp** [comment]
> I also think sound is not so important for now ... I had some read errors, always pressed retry and that fixed it, maybe they are more important than sound at the moment ...
> 
> But hey ADF reader works brilliantly thanks @dirkwhoffmann and @h5n1xp. You have done it !!

I’m very pleased we finally cracked the floppy problem, that burnt up so much of my time last year, it basically put this whole project back by a year!!

The read errors are very likely due to some IRQ CIA interaction weirdness... I need to think some more about what is going on.

**Comment by h5n1xp** [comment]
> If I remember correctly, the sample rate of each sound channel can be configured individually. Is this really easy to emulate? Maybe some kind of manual resampling is required 🤔.

Since I have a real-time emulated DMA, I would simply let the Audio DMA write the sample value (scaled) to the output buffer, with the index incrementing at the correct rate (a sort of sample and hold), this is easier to see than to explain, but I used this exact same technique with my MacOS protracker module player.

**Comment by h5n1xp** [comment]
> I also think sound is not so important for now ... I had some read errors, always pressed retry and that fixed it, maybe they are more important than sound at the moment ...
> 


Opening new issue about read errors
